### ISSUE TITLE
Full payment Example 

### ISSUE THREAD

**Issue by RyszardRzepa** [expo/stripe-expo#17]
Is this API just for creating credit card token?

It will be my first attempt to implement payments in the app, and I would like use stripe with expo.
Could you add a example of how to handle payment with this API?

1) registering credit card
2) paying for product 
3) removing registered credit card

Basically, the flow in the app will looks like. 
user must register credit card to make a payment -> with the token saved in the client, user can make a payment -> user can remove credit card(remove the token).

I don't have a clear picture how it should be implemented.

**Comment by jeff-da** [comment]
Hey! Its awesome to hear that you're working on payments with Expo.

Your flow looks right. After generating the token in the client (maybe with a couple input fields or a payment dialog), you should send the token to some kind of backend (for example, Node.js). There, you can charge the credit card (i.e. https://stripe.com/docs/api/node#charges). The Stripe Node.js docs are a good place to look in case you want to do anything else with the token (like a refund or creating a customer).

**Comment by RyszardRzepa** [comment]
Thanks for quick replay!

From what I learned, API keys should not be stored on the client. Is this code snippet, a right way to do it?

var stripe = require('stripe-client')('YOUR_PUBLISHABLE_STRIPE_API_KEY');

**Comment by jeff-da** [comment]
Stripe uses two separate API keys - a publishable key, and a secret key. The publishable key has no permissions that would be dangerous (i.e. the secret key must be used for anything to deal with actually processing the money).

If that code snippet is in the Expo application, make sure to use the publishable key (which is fine to be published in the client). You can use a similar code snippet in the Node.js server backend, but make sure to use your secret key so that Stripe allows you to create charges and process payments.

**Comment by RyszardRzepa** [comment]
@jeff-da Thanks again ;) 
I will play with stripe API now.

**Comment by dikaiosune** [comment]
Seems like the question here was answered, if this comes up again we might want to add a more general answer to docs. We also expect to have more fully integrated Stripe support in Expo in the coming months, so keep an eye out!
